### ISSUE TITLE
File replacement is not proper

### ISSUE THREAD

**Issue by manohartn** [basti1302/grunt-version-assets#1] opened 2015-07-23 00:29 UTC
Suppose i have two files : 
1) abc/def/xyz.js
2) ghi/klm/xyz.js 
(Notice there are two different files (but of same file names - xyz.js) in two different paths and i have both the files included in my jsp
as
<script src= "abc/def/xyz.js"/>
<script src= "ghi/klm/xyz.js "/>,
In the above case the grunt task replaces both the paths with same xyz hashed file.

**Comment by basti1302** [comment] 2015-07-24 06:45
duplicate of #2

**Closed as completed by basti1302** 2015-07-24 06:45 UTC
